### ISSUE TITLE
Cookie value for 'cf_clearance':

### ISSUE THREAD

**Issue by itanivalkyrie** [GekySan/SushiScan-DLer#1]
Bonjour, 
j'essaye sans succès de passer cette étape : 
![image](https://github.com/GekySan/SushiScan-DLer/assets/2438572/2792aecb-29dd-4a22-964c-7ae24b965ea2)
J'ai essayé plusieurs navigateurs que ce soit sous linux ou windows mais aucun succès. 
Je n'arrive pas à ajouter le cf_clearance même après installé le package. 
![image](https://github.com/GekySan/SushiScan-DLer/assets/2438572/f4848c2e-3e59-4d0c-92a4-8b03b02a77e0)

J'ai également tenté en utilisant un User Agent Spoofer et en utilisant le même que celui utilisé dans le code mais sans succès.

Merci pour ton travail et ton temps 👍

**Comment by antigeky** [comment]
Bonjour, je n'y avais pas pensé quand j'avais écris le code mais le cookie "cf_clearance" est spécifique à un certain User-Agent et ne fonctionnera pas si un User-Agent différent est utilisé.
Pour résoudre ce problème, il faut modifier le code en spécifiant votre propre User-Agent dans les fonctions make_request et download_image.
Je mettrai le code à jour avec un exemple dans le README !

EDIT: C'est fait.
