### ISSUE TITLE
Erreur 403

### ISSUE THREAD

**Issue by xavimaa** [GekySan/SushiScan-DLer#2]
Bonjour,

Je viens d'essayer SushiScan-DLer et je n'ai que des erreurs 403 : 

![image](https://github.com/GekySan/SushiScan-DLer/assets/82511742/2070b033-37cb-4523-b0c3-4db3eb2f489c)

Je ne sais pas si c'est moi qui est mal renseigné une info ?

Sinon même si ça ne fonctionne pas pour moi, merci pour ton travail et du partage offert ici !
Je me doute bien du casse tête que ça doit être de bypass cloudflare...

**Comment by antigeky** [comment]
Bonjour, il y avait un petit oubli, j'ai appliqué cette [modification](https://github.com/GekySan/SushiScan-DLer/commit/fda74fa01e8888a9c4093cbd0b839216d2daa821).

Télécharger la version mise à jour du code pour corriger le petit problème.
