### ISSUE TITLE
Access denied with status code 403. Please enter 'cf_clearance' cookie value.

### ISSUE THREAD

**Issue by sam5558** [GekySan/SushiScan-DLer#4]
Bonjour,

Je tiens tout d'abord à te remercier pour ce projet.

Je bloque à chaque fois sur l'étape du cf_clearance + User-agent. Je ne sais pas si je fais quelque chose de travers...
Je récupère le cf_clearance via extension de cookies et le user agent via une recherche google.

ça loop sur le process, pour l'url testé c'est celle-ci : https://sushiscan.net/catalogue/ayashimon/

Pour information je suis sur linux.

Toute aide est la bienvenue, merci.

![image](https://github.com/user-attachments/assets/affdf3f8-408b-4246-b55e-7edb47ff1307)

**Comment by antigeky** [comment]
Bonjour, tout ce que tu as fais est bon. J'ai effectué 1 test, et il semble qu'il y ait un souci, des modifications ont été apportées au site.
Je vais analyser le problème et (normalement) mettre à jour le code dans les prochains jours.

**Comment by antigeky** [comment]
Le code a été mis à jour ! J'ai effectué un test avec [Ayashimon](https://sushiscan.net/catalogue/ayashimon/), et tout fonctionne correctement.

**Comment by sam5558** [comment]
Hello @GekySan,
Vraiment désolé de réouvrir ce ticket, mais après que ça ait marché la semaine dernière.. ça ne marche plus cette semaine.
Je viens de revérifier à l'instant et ça ne marche pas : 
![image](https://github.com/user-attachments/assets/9ee599ae-545a-436d-9106-1ebcbe3b860d)

Je ne sais pas si c'est quelque chose qui a changé sur le site depuis la dernière fois ou si c'est moi qui rate un copier coller :smiling_face_with_tear: 
Si tu peux vérifier de ton côté :pray:

J'ai testé sur cet article : 
https://sushiscan.net/catalogue/1-meurtres-dans-le-decagone/

Cordialement

**Comment by antigeky** [comment]
Hello, ça fonctionne avec "Meurtres dans le décagone", tu peux re-test en vérifiant tout ce que tu as mis ?

**Comment by sam5558** [comment]
J'ai testé sur 3 navigateurs différents (chromium, librewolf, firefox) ça n'a pas l'air de marcher.. ça redemande le cf_clearance à chaque fois.
J'ai aussi supprimé le dossier SushiScan-DLer puis récupéré en git clone pour être sur que je suis sur une version saine mais ça marche pas.
Bizzare.

**Comment by antigeky** [comment]
J'ai effectué un test sur Ubuntu, cela ne fonctionne pas, j'ai le même problème que toi.
Je sais que ça venait de la librairie HTTP, j'ai (re)changé en utilisant un [wrapper de curl](https://github.com/lexiforest/curl_cffi), test en récupérant la nouvelle version et dis moi si c'est bon, n'oublie pas d'installer la nouvelle librairie.

**Comment by aboudiom59** [comment]
Comment est ce qu'on récupère cf_clearance?

**Comment by antigeky** [comment]
> Comment est ce qu'on récupère cf_clearance?

1. Accédez au site.
2. Complétez le captcha Cloudflare Turnstile.
3. Fermez l'onglet, puis ouvrez-en un nouveau.
4. Ouvrez la DevTools.
5. Dans l'onglet "Network", cochez l'option "Preserve log".
6. Accédez de nouveau au site. (Si le site se ferme automatiquement, c'est normal, c'est dû à l'anti-debugger.)
7. Filtrez en tapant "sushiscan", puis cliquez sur le premier.
8. Descendez jusqu'aux "Request Headers" et copiez le cookie.

![image](https://github.com/user-attachments/assets/6356ec2b-c852-4a70-848f-2d970d2e6d8e)
